'''
Description: 
Author: F.O.X
Date: 2021-03-23 19:24:43
LastEditor: F.O.X
LastEditTime: 2021-04-09 16:11:02
'''

ERROR_CODE = {
    0: "AT_SUCCESS",
    1: "AT_ERR_NOTINITIALISED",
    2: "AT_ERR_NOTIMPLEMENTED",
    3: "AT_ERR_READONLY",
    4: "AT_ERR_NOTREADABLE",
    5: "AT_ERR_NOTWRITABLE",
    6: "AT_ERR_OUTOFRANGE",
    7: "AT_ERR_INDEXNOTAVAILABLE",
    8: "AT_ERR_INDEXNOTIMPLEMENTED",
    9: "AT_ERR_EXCEEDEDMAXSTRINGLENGTH",
    10: "AT_ERR_CONNECTION",
    11: "AT_ERR_NODATA",
    12: "AT_ERR_INVALIDHANDLE",
    13: "AT_ERR_TIMEDOUT",
    14: "AT_ERR_BUFFERFULL",
    15: "AT_ERR_INVALIDSIZE",
    16: "AT_ERR_INVALIDALIGNMENT",
    17: "AT_ERR_COMM",
    18: "AT_ERR_STRINGNOTAVAILABLE",
    19: "AT_ERR_STRINGNOTIMPLEMENTED",
    20: "AT_ERR_NULL_FEATURE",
    21: "AT_ERR_NULL_HANDLE",
    22: "AT_ERR_NULL_IMPLEMENTED_VAR",
    23: "AT_ERR_NULL_READABLE_VAR",
    24: "AT_ERR_NULL_READONLY_VAR",
    25: "AT_ERR_NULL_WRITABLE_VAR",
    26: "AT_ERR_NULL_MINVALUE",
    27: "AT_ERR_NULL_MAXVALUE",
    28: "AT_ERR_NULL_VALUE",
    29: "AT_ERR_NULL_STRING",
    30: "AT_ERR_NULL_COUNT_VAR",
    31: "AT_ERR_NULL_ISAVAILABLE_VAR",
    32: "AT_ERR_NULL_MAXSTRINGLENGTH",
    33: "AT_ERR_NULL_EVCALLBACK",
    34: "AT_ERR_NULL_QUEUE_PTR",
    35: "AT_ERR_NULL_WAIT_PTR",
    36: "AT_ERR_NULL_PTRSIZE",
    37: "AT_ERR_NOMEMORY",
    38: "AT_ERR_DEVICEINUSE",
    39: "AT_ERR_DEVICENOTFOUND",
    100: "AT_ERR_HARDWARE_OVERFLOW"
}


class AndorError(Exception):
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return(ERROR_CODE[self.value])
